### ISSUE TITLE
cdk bootstrap doesn't work

### ISSUE THREAD

**Issue by Ascenter** [aws-quickstart/quickstart-swift-digital-connectivity#15]
user123@Ivans-MBP-2 quickstart-swift-digital-connectivity % cdk bootstrap 057086088767/us-east-1
jsii.errors.JavaScriptError: 
  TypeError: Cannot set property conditions of [object Object] which has only a getter
      at new PolicyStatementWithCondition (/private/var/folders/w2/pkm_05qd6h15td95ynltylv80000gn/T/jsii-kernel-LSWR3B/node_modules/cdk-iam-floyd/lib/shared/policy-statement/2-conditions.js:19:25)
      at new PolicyStatementWithActions (/private/var/folders/w2/pkm_05qd6h15td95ynltylv80000gn/T/jsii-kernel-LSWR3B/node_modules/cdk-iam-floyd/lib/shared/policy-statement/3-actions.js:17:9)
      at new PolicyStatementWithResources (/private/var/folders/w2/pkm_05qd6h15td95ynltylv80000gn/T/jsii-kernel-LSWR3B/node_modules/cdk-iam-floyd/lib/shared/policy-statement/4-resources.js:14:9)
      at new PolicyStatementWithEffect (/private/var/folders/w2/pkm_05qd6h15td95ynltylv80000gn/T/jsii-kernel-LSWR3B/node_modules/cdk-iam-floyd/lib/shared/policy-statement/5-effect.js:15:1)
      at new PolicyStatementWithPrincipal (/private/var/folders/w2/pkm_05qd6h15td95ynltylv80000gn/T/jsii-kernel-LSWR3B/node_modules/cdk-iam-floyd/lib/shared/policy-statement/6-principals.js:21:9)
      at new PolicyStatementWithCDKPrincipal (/private/var/folders/w2/pkm_05qd6h15td95ynltylv80000gn/T/jsii-kernel-LSWR3B/node_modules/cdk-iam-floyd/lib/shared/policy-statement/7-principals-CDK.js:16:9)
      at new PolicyStatement (/private/var/folders/w2/pkm_05qd6h15td95ynltylv80000gn/T/jsii-kernel-LSWR3B/node_modules/cdk-iam-floyd/lib/shared/policy-statement/9-final.js:12:1)
      at new Ec2 (/private/var/folders/w2/pkm_05qd6h15td95ynltylv80000gn/T/jsii-kernel-LSWR3B/node_modules/cdk-iam-floyd/lib/generated/ec2.js:19:9)
      at KeyPair.ensureLambda (/private/var/folders/w2/pkm_05qd6h15td95ynltylv80000gn/T/jsii-kernel-LSWR3B/node_modules/cdk-ec2-key-pair/lib/index.js:152:17)
      at new KeyPair (/private/var/folders/w2/pkm_05qd6h15td95ynltylv80000gn/T/jsii-kernel-LSWR3B/node_modules/cdk-ec2-key-pair/lib/index.js:95:28)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 21, in <module>
    main_stack = SwiftMain(app, "SWIFTMain-" + region, env=environment,
  File "/Users/user123/Library/Python/3.8/lib/python/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/user123/Documents/Projects/SWIFT in AWS/Code/quickstart-swift-digital-connectivity/swift_main_stack/main.py", line 51, in __init__
    KeyPair(self, "OperatorKeyPair2", name="OperatorKeyPair2",
  File "/Users/user123/Library/Python/3.8/lib/python/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/user123/Library/Python/3.8/lib/python/site-packages/cdk_ec2_key_pair/__init__.py", line 249, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "/Users/user123/Library/Python/3.8/lib/python/site-packages/jsii/_kernel/__init__.py", line 290, in create
    response = self.provider.create(
  File "/Users/user123/Library/Python/3.8/lib/python/site-packages/jsii/_kernel/providers/process.py", line 344, in create
    return self._process.send(request, CreateResponse)
  File "/Users/user123/Library/Python/3.8/lib/python/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Cannot set property conditions of [object Object] which has only a getter

**Comment by ruvimrd** [comment]
Hey @Ascenter, were you able to get past this issue?
